// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about-us": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/blogs/:id": {
    params: {
      "id": string;
    };
  };
  "/create-blog": {
    params: {};
  };
  "/blog-categories": {
    params: {};
  };
  "/add-blog-category": {
    params: {};
  };
  "/blog-categories/:id": {
    params: {
      "id": string;
    };
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/about-us" | "/blogs" | "/blogs/:id" | "/create-blog" | "/blog-categories" | "/add-blog-category" | "/blog-categories/:id" | "/login";
  };
  "pages/Homepage.jsx": {
    id: "pages/Homepage";
    page: "/";
  };
  "pages/AboutUs.jsx": {
    id: "pages/AboutUs";
    page: "/about-us";
  };
  "pages/Blogs.jsx": {
    id: "pages/Blogs";
    page: "/blogs";
  };
  "pages/EditBlog.jsx": {
    id: "pages/EditBlog";
    page: "/blogs/:id";
  };
  "pages/CreateABlog.jsx": {
    id: "pages/CreateABlog";
    page: "/create-blog";
  };
  "pages/BlogCategories.jsx": {
    id: "pages/BlogCategories";
    page: "/blog-categories";
  };
  "pages/EditBlogCategory.jsx": {
    id: "add-blog-category";
    page: "/add-blog-category";
  } | {
    id: "edit-blog-category";
    page: "/blog-categories/:id";
  };
  "pages/Login.jsx": {
    id: "pages/Login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "pages/Homepage": typeof import("./src/pages/Homepage.jsx");
  "pages/AboutUs": typeof import("./src/pages/AboutUs.jsx");
  "pages/Blogs": typeof import("./src/pages/Blogs.jsx");
  "pages/EditBlog": typeof import("./src/pages/EditBlog.jsx");
  "pages/CreateABlog": typeof import("./src/pages/CreateABlog.jsx");
  "pages/BlogCategories": typeof import("./src/pages/BlogCategories.jsx");
  "add-blog-category": typeof import("./src/pages/EditBlogCategory.jsx");
  "edit-blog-category": typeof import("./src/pages/EditBlogCategory.jsx");
  "pages/Login": typeof import("./src/pages/Login.jsx");
};